# Cramer's rule

In [1]:
import numpy as np

In [2]:
# 3x1 + x2 = 4
# 2x1 + x2 = 3

In [3]:
A = np.array([[3,1], [2,1]])
B = np.array([4,3])
A

array([[3, 1],
       [2, 1]])

In [4]:
detA = np.linalg.det(A)
detA

1.0000000000000002

In [5]:
# Replace first column
C = np.copy(A)
C[:, 0] = B
C

array([[4, 1],
       [3, 1]])

In [6]:
A

array([[3, 1],
       [2, 1]])

In [7]:
x1 = np.linalg.det(C)/detA
x1

0.9999999999999998

In [8]:
C = np.copy(A)
C[:, 1] = B
C

array([[3, 4],
       [2, 3]])

In [9]:
A

array([[3, 1],
       [2, 1]])

In [10]:
x2 = np.linalg.det(C)/detA
x2

1.0000000000000002