## Statistical Op

In [1]:
import numpy as np;

In [7]:
A = np.array([1,2,3])

In [8]:
np.mean(A)

2.0

In [9]:
B = np.array([1,2,3])

In [10]:
np.var(B)

0.6666666666666666

In [11]:
C = np.array([1,2,3])

In [12]:
np.std(C)

0.816496580927726

In [13]:
D = np.array([1,2,3])

In [14]:
E = np.array([1,2,3])

In [15]:
D*E

array([1, 4, 9])

In [16]:
F = np.array([1,2,3])

In [17]:
G = np.array([1,2,3])

In [18]:
np.cov(F, G)

array([[1., 1.],
       [1., 1.]])

In [38]:
X = np.array([100,110,105,100,95])

In [39]:
Y = np.array([150,148,155,155,100])

In [20]:
np.square(X)

array([1, 4, 9])

In [40]:
def covar(X, Y):
    Z = X*Y
    print('xy', Z)
    x1 = np.mean(X)
    y1 = np.mean(Y)
    z1 = np.mean(Z)
    print('Mean of X', x1)
    print('Mean of Y', y1)
    print('Mean of XY', z1)
    return (z1 - (x1*y1))

In [41]:
qwe = covar(X, Y)
print('covariance: ', qwe)

xy [15000 16280 16275 15500  9500]
Mean of X 102.0
Mean of Y 141.6
Mean of XY 14511.0
covariance:  67.80000000000109


In [42]:
a = np.std(X)
a

5.0990195135927845

In [43]:
b = np.std(Y)
b

20.981896959045432

In [44]:
a*b


106.98710202636576