# Eigen value & SVD

In [1]:
import numpy as np;
A = np.array([[3,2,2],[2,3,2]])

In [2]:
A

array([[3, 2, 2],
       [2, 3, 2]])

In [3]:
B = np.transpose(A)
B

array([[3, 2],
       [2, 3],
       [2, 2]])

In [4]:
C = np.dot(B,A)
C

array([[13, 12, 10],
       [12, 13, 10],
       [10, 10,  8]])

In [5]:
l = np.linalg.eig(C)
l

(array([3.30000000e+01, 1.00000000e+00, 1.01084336e-16]),
 array([[-6.15457455e-01, -7.07106781e-01, -3.48155312e-01],
        [-6.15457455e-01,  7.07106781e-01, -3.48155312e-01],
        [-4.92365964e-01,  9.09032207e-16,  8.70388280e-01]]))

In [6]:
SVD = np.linalg.svd(C)
SVD

(array([[-6.15457455e-01,  7.07106781e-01, -3.48155312e-01],
        [-6.15457455e-01, -7.07106781e-01, -3.48155312e-01],
        [-4.92365964e-01,  1.31965976e-15,  8.70388280e-01]]),
 array([3.30000000e+01, 1.00000000e+00, 1.63797695e-15]),
 array([[-6.15457455e-01, -6.15457455e-01, -4.92365964e-01],
        [ 7.07106781e-01, -7.07106781e-01,  2.57169186e-15],
        [ 3.48155312e-01,  3.48155312e-01, -8.70388280e-01]]))

In [7]:
SVD2 = np.linalg.svd(A)
SVD2

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5.74456265, 1.        ]),
 array([[-6.15457455e-01, -6.15457455e-01, -4.92365964e-01],
        [-7.07106781e-01,  7.07106781e-01, -1.38777878e-17],
        [-3.48155312e-01, -3.48155312e-01,  8.70388280e-01]]))