# MATRIX OPERATIONS

In [1]:
import numpy as np;

In [2]:
A = np.array([[1,2,-1,-2,0], [2,4,-1,1,0], [3,6,-1,4,1], [0,0,1,5,0]])
A


array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

## Transpose

In [3]:
np.transpose(A)

array([[ 1,  2,  3,  0],
       [ 2,  4,  6,  0],
       [-1, -1, -1,  1],
       [-2,  1,  4,  5],
       [ 0,  0,  1,  0]])

In [4]:
B = np.array([[1,2,-1,-2,0], [2,4,-1,1,0], [3,6,-1,4,1], [0,0,1,5,0]])
B

array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

## Arithmetic Operations

In [5]:
A+B

array([[ 2,  4, -2, -4,  0],
       [ 4,  8, -2,  2,  0],
       [ 6, 12, -2,  8,  2],
       [ 0,  0,  2, 10,  0]])

In [6]:
A

array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

In [7]:
B


array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

In [9]:
A+B

array([[10,  8,  8,  9,  9],
       [11, 13,  9, 18, 10],
       [11, 13,  5, 12, 12]])

In [8]:
A-B

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
A*B

array([[ 1,  4,  1,  4,  0],
       [ 4, 16,  1,  1,  0],
       [ 9, 36,  1, 16,  1],
       [ 0,  0,  1, 25,  0]])

In [14]:
A

array([[4, 6, 2, 8, 6],
       [9, 6, 1, 9, 5],
       [2, 4, 4, 7, 9]])

## Matrix Multiplication

In [10]:
A #3*5

array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

In [11]:
C = np.array([[1,2,-1,-2,0], [2,4,-1,1,0], [3,6,-1,4,1], [0,0,1,5,0]])
C

array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

In [12]:
A.shape


(4, 5)

In [13]:
C.shape

(4, 5)

In [16]:
A.ndim



2

In [17]:
C.ndim

2

In [15]:
Z = np.cross(A,C)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [18]:
np.dot(A, C)

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [27]:
A.dot(C)

array([[156, 108, 192],
       [181, 107, 209],
       [162, 125, 195]])

## Determinant

In [19]:
np.det(A)

AttributeError: module 'numpy' has no attribute 'det'

In [20]:

np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

In [34]:
D = np.random.randint(1,5, size=(2,2))
D

array([[2, 1],
       [1, 4]])

In [36]:
np.linalg.det(D)

7.000000000000001

In [37]:
E = np.array([[1,2,-1,-2,0], [2,4,-1,1,0], [3,6,-1,4,1], [0,0,1,5,0]])
E

array([[4, 4, 1],
       [4, 1, 2],
       [4, 2, 4]])

In [39]:
np.linalg.det(E)

-28.00000000000001

## Inverse

In [40]:
np.linalg.inv(D)

array([[ 0.57142857, -0.14285714],
       [-0.14285714,  0.28571429]])

In [41]:
np.linalg.inv(E)

array([[ 0.        ,  0.5       , -0.25      ],
       [ 0.28571429, -0.42857143,  0.14285714],
       [-0.14285714, -0.28571429,  0.42857143]])

## Matrix Rank

In [43]:
F = np.array([[1,2,-1,-2,0], [2,4,-1,1,0], [3,6,-1,4,1], [0,0,1,5,0]])
F

array([[ 1,  2, -1, -2,  0],
       [ 2,  4, -1,  1,  0],
       [ 3,  6, -1,  4,  1],
       [ 0,  0,  1,  5,  0]])

In [44]:
np.linalg.matrix_rank(F)

3