# NumPy Computations

In [1]:
import numpy as np

In [3]:
# create an array of 25 elements between 1 and 50 (not inclusive)
arr = np.arange(1,50,2)

arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [4]:
# reshape this 1-D to 2-D array

arr2 = arr.reshape(5,5)
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [ ]:
#    0   1   2   3   4
# 0 [ 1,  3,  5,  7,  9], -5
# 1 [11, 13, 15, 17, 19], -4
# 2 [21, 23, 25, 27, 29], -3
# 3 [31, 33, 35, 37, 39], -2
# 4 [41, 43, 45, 47, 49]] -1
#    -5  -4  -3  -2  -1

### Accessing indivdual elements of a NumPy Array

In [5]:
#           0  1  2  3  4
# arr1 = (([4, 7, 3, 1, 9]))
#          -5 -4 -3 -2 -1

arr1 = np.array([4,7,3,1,9])
arr1

array([4, 7, 3, 1, 9])

In [6]:
arr1[2]

3

In [7]:
arr1[-3]

3

In [8]:
# Modifying elements of a NumPy array
arr1[3] = 786

arr1

array([  4,   7,   3, 786,   9])

### Arithmetic with NumPy Arrays

In [10]:
arr3 = np.array([[1,2,3], [4,5,6]])

arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Let's take a deep copy of arr3
arr4 = np.copy(arr3)
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Adding two NumPy Arrays
# NumPy performs elementwise addition
arr3 + arr4

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
a = [1,2]
b = [3,4]

a + b

[1, 2, 3, 4]

In [15]:
# Subraction - elementwise operations

arr3 - arr4

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr3 * arr4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [19]:
#Inversing each element of the array (1/x)
# Floating point division

1/arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [21]:
# Double slash - integer division

15//arr3

array([[15,  7,  5],
       [ 3,  3,  2]], dtype=int32)

In [22]:
# Scalar multiplication
# Multiplying each element of the array with a scalar value
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr4 * 2.5

array([[ 2.5,  5. ,  7.5],
       [10. , 12.5, 15. ]])

In [24]:
arr4 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [25]:
# Taking cube of the elements
np.power(arr4, 3)

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [26]:
# Adding a scalar to each element of the array

np.add(arr4, 5)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

### Array Slicing

In [2]:
import numpy as np

In [3]:
arr1 = np.array([4,7,3,9,5])
arr1

array([4, 7, 3, 9, 5])

In [4]:
# Slice complete array
arr1[:]

array([4, 7, 3, 9, 5])

In [5]:
# Omitting starting number defaults to zero
arr1[:2]

array([4, 7])

In [6]:
# Omitting ending number defaults to end of the list
arr1[3:]

array([9, 5])

In [7]:
#Slicing with a step value
arr1[::2]

array([4, 3, 5])

In [8]:
arr2 = np.arange(1,50,2).reshape(5,5)
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [11]:
#Accessing individual elements
print(arr2[3][2])
print(arr2[3,2])

35
35


In [13]:
print(arr2[-2][-4])
print(arr2[-2,-4])

33
33


In [14]:
#Slicing all rows and all columns
arr2[:,:]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [15]:
# All rows, columns 0 and 1
arr2[:, :2]

array([[ 1,  3],
       [11, 13],
       [21, 23],
       [31, 33],
       [41, 43]])

In [16]:
# All rows, columns at index 2 and 3
x = arr2[:, 2:4]

x

array([[ 5,  7],
       [15, 17],
       [25, 27],
       [35, 37],
       [45, 47]])

In [19]:
print(x.shape)
print(x.ndim)
print(type(x))

(5, 2)
2
<class 'numpy.ndarray'>


In [20]:
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [21]:
# Rows 3 and 4, but all columns
arr2[3:5, :]

array([[31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [25]:
x = arr2[2]

print(x)
print(x.shape)
print(x.ndim)
print(type(x))

[21 23 25 27 29]
(5,)
1
<class 'numpy.ndarray'>


In [29]:
y = arr2[:, 3]

print(y)
print(y.shape)
print(y.ndim)
print(type(y))

[ 7 17 27 37 47]
(5,)
1
<class 'numpy.ndarray'>


In [32]:
z = arr2[:, 3:4]
print(z)
print(z.shape)
print(z.ndim)

[[ 7]
 [17]
 [27]
 [37]
 [47]]
(5, 1)
2


In [33]:
arr2[2:4, :]

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [34]:
arr2[2:4]

array([[21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [35]:
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [36]:
arr2[2:4, 3:5]

array([[27, 29],
       [37, 39]])

In [37]:
arr2[1:4:, 2]

array([15, 25, 35])

In [38]:
a = arr2[::2, 3]
a

array([ 7, 27, 47])

In [39]:
arr2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [40]:
b = arr2[4, 1::2]
b

array([43, 47])

In [41]:
c = arr2[1:4, 2:3]
c

array([[15],
       [25],
       [35]])

### Slice of numpy array points to the same array

In [42]:
a = [1,2,3,4,5]

b = a[1:4] # Slice elements 1, 2, 3

print(a)
print(b)

print(id(a))
print(id(b))

[1, 2, 3, 4, 5]
[2, 3, 4]
2315557932552
2315557932680


In [43]:
b[1] = 786
print(b)
print(a)

[2, 786, 4]
[1, 2, 3, 4, 5]


In [44]:
arr1 = np.array([4,7,3,9,5])
arr1

array([4, 7, 3, 9, 5])

In [45]:
sub_arr1 = arr1[:3]

sub_arr1

array([4, 7, 3])

In [46]:
sub_arr1[1] = 786

In [47]:
print(sub_arr1)
print(arr1)

[  4 786   3]
[  4 786   3   9   5]


In [48]:
# set all the elements of sub array to 1234
sub_arr1[:] = 1234

sub_arr1

array([1234, 1234, 1234])

In [49]:
arr1

array([1234, 1234, 1234,    9,    5])

In [50]:
arr1 = np.array([4,7,3,9,5])
arr1

array([4, 7, 3, 9, 5])

In [51]:
arr2 = arr1.copy()
arr2

array([4, 7, 3, 9, 5])

### Computations and Comparisons

In [52]:
arr5 = np.random.randint(2,10, size=(2,3))
arr5

array([[5, 6, 8],
       [9, 7, 8]])

In [53]:
arr6 = np.random.randint(2,10, size=(2,3))
arr6

array([[3, 9, 3],
       [7, 3, 6]])

In [56]:
arr5 > arr6

array([[ True, False,  True],
       [ True,  True,  True]])

In [55]:
arr5 == arr6

array([[False, False, False],
       [False, False, False]])

In [57]:
np.any(arr5 > arr6)

True

In [58]:
np.all(arr5 > arr6)

False

In [59]:
np.all(arr5 != arr6)

True

In [60]:
np.equal(arr5, 5)

array([[ True, False, False],
       [False, False, False]])

In [61]:
np.greater(arr6, 5)

array([[False,  True, False],
       [ True, False,  True]])

In [62]:
np.greater_equal(arr5, 9)

array([[False, False, False],
       [ True, False, False]])

### Computations - Aggregations

In [63]:
arr1

array([4, 7, 3, 9, 5])

In [64]:
arr1.sum()

28

In [65]:
np.sum(arr1)

28

In [66]:
arr1.min()

3

In [67]:
arr1.mean()

5.6

In [68]:
arr1.std()

2.1540659228538015

In [69]:
arr1.var()

4.64

In [70]:
# axis-0 - along the rows
# axis-1 - along the columns

arr5

array([[5, 6, 8],
       [9, 7, 8]])

In [71]:
np.sum(arr5, axis=0)

array([14, 13, 16])

In [72]:
np.sum(arr5, axis=1)

array([19, 24])

In [73]:
np.min(arr5, axis=0)

array([5, 6, 8])

In [74]:
np.min(arr5, axis=1)

array([5, 7])

### Boolean Indexing

In [75]:
names = np.array(['Leo', 'Ali', 'Fox', 'Leo', 'Fox', 'Ali', 'Max'])
names

array(['Leo', 'Ali', 'Fox', 'Leo', 'Fox', 'Ali', 'Max'], dtype='<U3')

In [76]:
# Create an numpy array of 7 rows and 4 columns
data = np.random.randint(-20, 20, 28).reshape(7,4)

data

array([[-19,  17,  -9,   0],
       [  7,   3,   8,   8],
       [  2,   0, -20,   0],
       [-14,  11,   2,  -3],
       [ 10, -18,  -9,  -5],
       [  3,   2,   9, -13],
       [  3,   2, -16, -11]])

In [77]:
names == 'Leo'

array([ True, False, False,  True, False, False, False])

In [78]:
#Apply this boolean array to our 2-D array above
# Select rows where 'Leo' is True
data[names == 'Leo']

array([[-19,  17,  -9,   0],
       [-14,  11,   2,  -3]])

In [79]:
# Select columns at index 1 and 2
data[names == 'Leo', 1:3]

array([[17, -9],
       [11,  2]])

In [80]:
# Select only column 4
data[names == 'Leo', 3]

array([ 0, -3])

In [81]:
names != 'Leo'

array([False,  True,  True, False,  True,  True,  True])

In [82]:
data[names != 'Leo']

array([[  7,   3,   8,   8],
       [  2,   0, -20,   0],
       [ 10, -18,  -9,  -5],
       [  3,   2,   9, -13],
       [  3,   2, -16, -11]])

In [84]:
data[~(names == 'Leo')]

array([[  7,   3,   8,   8],
       [  2,   0, -20,   0],
       [ 10, -18,  -9,  -5],
       [  3,   2,   9, -13],
       [  3,   2, -16, -11]])

In [86]:
onlyLeo = names == 'Leo'

In [87]:
data[onlyLeo]

array([[-19,  17,  -9,   0],
       [-14,  11,   2,  -3]])

In [88]:
data[~onlyLeo]

array([[  7,   3,   8,   8],
       [  2,   0, -20,   0],
       [ 10, -18,  -9,  -5],
       [  3,   2,   9, -13],
       [  3,   2, -16, -11]])

In [89]:
leo_or_fox = (names == 'Leo') | (names == 'Fox')

In [90]:
data[leo_or_fox]

array([[-19,  17,  -9,   0],
       [  2,   0, -20,   0],
       [-14,  11,   2,  -3],
       [ 10, -18,  -9,  -5]])

In [91]:
# Assign a value to all those elements that are not 'Ali'

data[names != 'Ali'] = 5

data

array([[  5,   5,   5,   5],
       [  7,   3,   8,   8],
       [  5,   5,   5,   5],
       [  5,   5,   5,   5],
       [  5,   5,   5,   5],
       [  3,   2,   9, -13],
       [  5,   5,   5,   5]])