# NumPy Arrays

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])

In [4]:
arr1

array([1, 2, 3])

In [5]:
arr1.dtype

dtype('int64')

In [6]:
arr1.shape

(3,)

In [7]:
arr1.size

3

In [8]:
type(arr1)

numpy.ndarray

## Comparinng between numPy array and python list

In [10]:
myArr = np.arange(10000) # numPy array
myList = list(range(10000)) # python list

In [12]:
%time for _ in range(10): myArr = myArr * 2

CPU times: user 613 µs, sys: 782 µs, total: 1.39 ms
Wall time: 706 µs


In [13]:
%time for _ in range(10): myList2 = [x*2 for x in myList]

CPU times: user 4.9 ms, sys: 698 µs, total: 5.6 ms
Wall time: 5.24 ms


## Properties of NumPy Array

In [14]:
# dtype -> data type of elements
# shape -> a tuple that idicates the size of each dimension
# ndim -> number of dimensions of the array
# size -> no. of elements in the array

In [16]:
arr2 = np.array([1,2, 3.4, 'FIle'])

In [18]:
arr2.dtype

dtype('<U32')

In [19]:
arr2.size

4

In [20]:
arr2.shape

(4,)

In [21]:
arr2.ndim

1

## Two Dimensional Arrays

In [22]:
arr2 = np.array([[1,2,3], [4,5,6,7]])

In [23]:
arr2

array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [25]:
arr3 = np.array([[1,2,3], [4,5,6]])

In [26]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr3.dtype

dtype('int64')

In [28]:
arr3.size

6

In [29]:
arr3.shape

(2, 3)

In [30]:
arr3.ndim

2

In [31]:
# Creating 2D nnumpy array with python lists
l1 = [1,2,3]
l2 = [4,5,6]
arr3 = np.array([l1,l2])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

# np.random

In [25]:
# Create random 2D array od size 4,5
import numpy as np
np.random.seed(1)
arr4 = np.random.randn(4,5)
print(np.mean(arr4))
arr4

-0.1333646364607294


array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521]])

In [6]:
arr4.dtype

dtype('float64')

In [35]:
arr5 = np.random.randint(10,30, size = (4,5))
arr5

array([[16, 29, 19, 27, 12],
       [17, 28, 25, 26, 27],
       [13, 18, 16, 18, 25],
       [10, 14, 26, 25, 29]])

In [36]:
arr5.dtype

dtype('int64')

In [37]:
# Generate a 3*3 array of random samples from a ormal distribution with 
# standard deviation of 4.5(sigma) and mean = 5
data = 4.5 * np.random.randn(3,3) + 5
data

array([[ 5.39881088,  1.72536623,  3.85684287],
       [ 1.60311842,  4.90653154, 12.61297132],
       [ 4.22652568, -1.43117022,  6.74552631]])

## Prepopulated Array (np.asarray)

In [38]:
arr1


array([1, 2, 3])

In [41]:
a2 = np.asarray(arr1)
a2

array([1, 2, 3])

In [42]:
a2 is arr1

True

In [43]:
id(a2)

4435544064

In [44]:
id(arr1)

4435544064

In [45]:
a2[0] = 456


In [46]:
a2

array([456,   2,   3])

In [47]:
arr1

array([456,   2,   3])

In [48]:
x = np.array([1,2,3], dtype = 'float32')
x

array([1., 2., 3.], dtype=float32)

In [49]:
y = np.asarray(x, dtype = 'int32')
y

array([1, 2, 3], dtype=int32)

In [50]:
y is x

False

# np.zeros

In [53]:
# Creatinng an array of 0s
a = np.zeros(3)
a

array([0., 0., 0.])

In [54]:
a = np.zeros(3, dtype = 'int32')
a

array([0, 0, 0], dtype=int32)

In [55]:
a = np.zeros((3,4), dtype = 'int32')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

# np.ones

In [56]:
# similarly we have ones function as well
a = np.ones(4, dtype = 'int32')
a

array([1, 1, 1, 1], dtype=int32)

In [60]:
a = np.ones((2,3), dtype = 'int32')
a

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

# np.empty

In [58]:
# Create an empty array
a = np.empty(5, dtype = 'int32')
a

array([16843009, 16843009, 16843009, 16843009, 16843009], dtype=int32)

In [59]:
a = np.empty((2,4), dtype = 'int32')
a

array([[          0, -2147483648,           0, -2147483648],
       [          2,           0,           0,      131072]], dtype=int32)

# np.arange

In [62]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
a = np.arange(10, 20, 2)
a

array([10, 12, 14, 16, 18])

In [68]:
a = np.arange(20, 10, -2)
a

array([20, 18, 16, 14, 12])

# np.linspace

In [69]:
a = np.linspace(2,10,2) # equally spaced
a

array([ 2., 10.])

In [70]:
a = np.linspace(2,10,10)
a

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [73]:
a = np.linspace(2,10,9)
a

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# np.zeros_like


In [75]:
a = np.random.randint(4, 100, (3,5))
a

array([[65, 16, 65, 65, 90],
       [69, 32, 49, 28, 98],
       [69, 51, 92, 85, 84]])

In [76]:
b = np.zeros_like(a)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [77]:
b[0] = 2
b

array([[2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [78]:
a

array([[65, 16, 65, 65, 90],
       [69, 32, 49, 28, 98],
       [69, 51, 92, 85, 84]])

# np.ones_like

In [79]:
b = np.ones_like(a)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# np.full & np.full_like

In [81]:
a = np.full((4,2), 23)
a

array([[23, 23],
       [23, 23],
       [23, 23],
       [23, 23]])

In [82]:
b = np.full_like(a, 31)
b

array([[31, 31],
       [31, 31],
       [31, 31],
       [31, 31]])

# fill

In [83]:
b.fill(2)
b

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

# np.eye & np.identity (Identity matrix)

In [84]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
a = np.eye(3, dtype = 'int32')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [87]:
a = np.eye(4,3) # doesn't make sense
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [88]:
a = np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [89]:
a = np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

In [90]:
a = np.identity(3,5)
a

TypeError: data type not understood

In [92]:
a = np.identity(4, dtype='int32')
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

# Type Casting

In [93]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [94]:
a.dtype

dtype('int64')

In [96]:
# Int -> float
b = a.astype(np.float64)
b

array([1., 2., 3., 4.])

In [98]:
a = np.random.randn(2,3)
a

array([[-0.01749583, -0.3401678 ,  0.74565243],
       [ 0.56116738, -0.19690056, -0.03471877]])

In [99]:
# float -> int
b = a.astype(np.int32)
b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [101]:
a = np.array([1.2, 3.4])
b = a.astype(np.int32)
b

array([1, 3], dtype=int32)